In [1]:
import numpy as np

In [2]:
#Создать массив из 10-ти нулей.
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
#Создать массив из 10-ти единиц.
a=np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [4]:
#Создать массив из 10-ти пятёрок.
a=np.ones(10)*5
print(a)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [5]:
#Создать массив из целых чисел от 10-ти до 50-ти.
a=np.arange(10,51)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [6]:
#Создать массив из чётных чисел от 10-ти до 50-ти.
a=np.arange(10,51,2)
print(a)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [7]:
#Создать матрицу 3*3 с числами от 0 до 8.
a=np.arange(9) . reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
#Создать единичную матрицу 3x3
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
#Использовать NumPy для генерации случайного числа от 0 до 1.
a=np.random.rand()
print(a)

0.40348604750104333


In [10]:
#Использовать NumPy для генерации массива из 25-ти случайных чисел, взятых из стандартного нормального распределения.
a=np.random.rand(25)
print(a)

[0.93458396 0.91462496 0.16035975 0.5381568  0.46504353 0.37074591
 0.81327201 0.59289263 0.93815289 0.73037231 0.91411721 0.69170909
 0.12262411 0.66620286 0.65503052 0.94486566 0.81252052 0.66919487
 0.72833939 0.43158923 0.77717333 0.13194516 0.26291883 0.03881812
 0.79691946]


In [11]:
#Создать матрицу, используя функции библиотеки NumPy.
a=np.arange(0.01,1.01,0.01) . reshape(10,10)
print(a)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [18]:
#это наша стартовая матрица
mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [13]:
#Написать код, который вернет следующую матрицу из стартовой.
a=np.arange(1,26).reshape(5,5)
print(mat[2:5, 1:5])

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [14]:
#Написать код обращения к элементу, который вернет значение  20 из стартовой матрицы задачи l
mat=np.arange(1,26).reshape(5,5)
print(mat[3][4])

20


In [15]:
#Написать код к стартовой матрице задачи l
mat=np.arange(1,26).reshape(5,5)
print(mat[0:3, 1:2])

[[ 2]
 [ 7]
 [12]]


In [16]:
#Написать код к стартовой матрице задачи l
mat=np.arange(1,26).reshape(5,5)
print(mat[4, :])

[21 22 23 24 25]


In [17]:
#Написать код к стартовой матрице задачи l
mat=np.arange(1,26).reshape(5,5)
print(mat[3:5, :])

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [19]:
#Получить сумму всех значений в стартовой матрице mat.
mat=np.arange(1,26).reshape(5,5)
print(mat.sum())

325


In [20]:
#Получить стандартное отклонение к стартовой матрице mat.
mat=np.arange(1,26).reshape(5,5)
print(mat.std())

7.211102550927978


In [23]:
#Получить сумму значений в колонках к стартовой матрице mat.
mat=np.arange(1,26).reshape(5,5)
print(mat)
print('SUM')
print(mat.sum(axis=0))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
SUM
[55 60 65 70 75]
